[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask-cors>=5.0.1",
    "flask>=3.1.0",
    "openai>=1.65.2",
]
